#
# These ENV variables are required to build the project on Travis-ci
# GH_TOKEN : Github Token
# GH_USER_NAME : Github user
# GH_USER_EMAIL : Github email (clear)
# GH_REF : Github repo (e.g. -> github.com:bucharest-gold/litoria.git) (clear)
# NPM_TOKEN : npmjs.org Token to access the npmjs.org server where we deploy this module
#
sudo: required
dist: trusty
language: node_js
node_js:
#  - "4"
#  - "5"
  - "6"
env:
  global:
  - GIT_REPO_ASCIIDOCTOR_STYLESHEET: "https://github.com/asciidoctor/asciidoctor-stylesheet-factory.git"
  - LITORIA_BUILD: "$TRAVIS_BUILD_DIR/build"
  - GIT_STYLES_DIR: "$LITORIA_BUILD/asciidoctor-styles"
before_install:
  - "npm install -g npm@latest"
install:
  - gem install --version '0.12.7' compass
  - gem install --version '4.3.2' zurb-foundation
before_script:
  - echo "Git clone the Asciidoctor Stylesheet Factory project and compile the css files using ruby compass"
  - git clone $GIT_REPO_ASCIIDOCTOR_STYLESHEET $GIT_STYLES_DIR
  - cd $GIT_STYLES_DIR
  - compass compile
  - mkdir -p $LITORIA_BUILD/assets/css
  - mv $GIT_STYLES_DIR/stylesheets/* $LITORIA_BUILD/assets/css
script:
  - cd $TRAVIS_BUILD_DIR && make
after_success:
  - npm install -g ci-publish
  - make clean
  - cp -r bin examples lib templates test package.json Makefile $LITORIA_BUILD/
  - cd $LITORIA_BUILD
  - rm -rf asciidoctor-styles
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - echo "*.log" >> .gitignore
  - echo "Increment version of the module"
#  - npm version patch
  - ls -la .
  - echo "Commit and push the branch release"
  - git add .
  - git commit -m "Deploy the release branch"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:release > /dev/null 2>&1
#  - echo "Publish the module to npmjs.org repo"
#  - ci-publish || true
notifications:
  irc: "chat.freenode.net#brass-monkey"