source: "./source" # directory path or name of the file to be processed: ./source/simple.adoc
destination: "./generated"

file_to_inline: "./generated/output.html"
file_inlined: "./generated/output-inlined.html"

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  icons: 'font'
  # linkcss: 'true' # Don't use this option if you want to embed the CSS

options:
  doctype: 'article'
  to_dir: 'generated'
  to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded

