# source: "./source" # or could be a directory eg. ./examples
source: "./generated_content/hol.html" # or could be a directory eg. ./examples
destination: "./generated"

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  icons: 'font'
  # linkcss: 'true' # Don't use this option if you want to embed the CSS

options:
  doctype: 'article'
  to_dir: 'generated'
  to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded

